// Code generated by goyacc -o strace.go -p Strace strace.y. DO NOT EDIT.

// nolint
//
//line strace.y:2
package parser

import __yyfmt__ "fmt"

//line strace.y:3

import (
//"fmt"
)

//line strace.y:12
type StraceSymType struct {
	yys               int
	data              string
	val_int           int64
	val_double        float64
	val_uint          uint64
	val_field         *Field
	val_call          *Call
	val_macro         *macroType
	val_int_type      *intType
	val_identifiers   []*BufferType
	val_buf_type      *BufferType
	val_group_type    *GroupType
	val_pointer_type  *PointerType
	val_flag_type     *flagType
	val_type          IrType
	val_types         []IrType
	val_parenthetical *parenthetical
	val_syscall       *Syscall
}

const STRING_LITERAL = 57346
const IPV4 = 57347
const IPV6 = 57348
const IDENTIFIER = 57349
const FLAG = 57350
const DATETIME = 57351
const SIGNAL_PLUS = 57352
const SIGNAL_MINUS = 57353
const MAC = 57354
const INT = 57355
const UINT = 57356
const DOUBLE = 57357
const QUESTION = 57358
const ARROW = 57359
const OR = 57360
const AND = 57361
const LOR = 57362
const TIMES = 57363
const LAND = 57364
const LEQUAL = 57365
const ONESCOMP = 57366
const LSHIFT = 57367
const RSHIFT = 57368
const NOT = 57369
const COMMA = 57370
const LBRACKET = 57371
const RBRACKET = 57372
const LBRACKET_SQUARE = 57373
const RBRACKET_SQUARE = 57374
const LPAREN = 57375
const RPAREN = 57376
const EQUALS = 57377
const UNFINISHED = 57378
const RESUMED = 57379
const NULL = 57380
const AT = 57381
const COLON = 57382
const KEYWORD = 57383
const NOTYPE = 57384
const NOFLAG = 57385
const EQUAL = 57386

var StraceToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"STRING_LITERAL",
	"IPV4",
	"IPV6",
	"IDENTIFIER",
	"FLAG",
	"DATETIME",
	"SIGNAL_PLUS",
	"SIGNAL_MINUS",
	"MAC",
	"INT",
	"UINT",
	"DOUBLE",
	"QUESTION",
	"ARROW",
	"OR",
	"AND",
	"LOR",
	"TIMES",
	"LAND",
	"LEQUAL",
	"ONESCOMP",
	"LSHIFT",
	"RSHIFT",
	"NOT",
	"COMMA",
	"LBRACKET",
	"RBRACKET",
	"LBRACKET_SQUARE",
	"RBRACKET_SQUARE",
	"LPAREN",
	"RPAREN",
	"EQUALS",
	"UNFINISHED",
	"RESUMED",
	"NULL",
	"AT",
	"COLON",
	"KEYWORD",
	"NOTYPE",
	"NOFLAG",
	"EQUAL",
}

var StraceStatenames = [...]string{}

const StraceEofCode = 1
const StraceErrCode = 2
const StraceInitialStackSize = 16

//line yacctab:1
var StraceExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const StracePrivate = 57344

const StraceLast = 680

var StraceAct = [...]uint8{
	30, 110, 96, 121, 98, 41, 7, 97, 88, 135,
	41, 108, 37, 12, 2, 12, 69, 32, 68, 72,
	4, 71, 34, 35, 122, 51, 109, 62, 70, 39,
	31, 60, 61, 53, 12, 12, 144, 142, 25, 57,
	24, 54, 29, 55, 3, 140, 8, 41, 56, 128,
	33, 12, 12, 103, 32, 125, 138, 111, 64, 34,
	35, 83, 14, 127, 12, 12, 12, 67, 94, 41,
	53, 123, 120, 93, 118, 40, 12, 66, 52, 29,
	126, 57, 41, 54, 5, 55, 89, 33, 73, 74,
	56, 105, 65, 50, 99, 12, 124, 119, 12, 117,
	12, 116, 84, 86, 34, 35, 75, 76, 77, 78,
	79, 80, 81, 82, 43, 44, 52, 50, 136, 49,
	136, 45, 46, 113, 114, 136, 115, 136, 136, 87,
	63, 12, 104, 111, 90, 106, 91, 73, 112, 136,
	136, 136, 1, 136, 136, 136, 136, 36, 137, 136,
	137, 136, 136, 11, 136, 137, 27, 137, 137, 43,
	44, 26, 50, 48, 49, 58, 45, 46, 141, 137,
	137, 137, 59, 137, 137, 137, 137, 147, 28, 137,
	13, 137, 137, 139, 137, 9, 10, 0, 143, 147,
	145, 0, 50, 147, 49, 147, 45, 46, 147, 0,
	147, 147, 148, 147, 150, 0, 151, 0, 153, 16,
	19, 20, 21, 32, 17, 0, 0, 18, 34, 35,
	0, 44, 0, 50, 22, 49, 0, 45, 46, 15,
	100, 101, 0, 102, 25, 107, 24, 50, 29, 0,
	0, 45, 46, 23, 0, 0, 33, 16, 19, 20,
	21, 32, 17, 0, 0, 18, 34, 35, 0, 0,
	0, 0, 22, 0, 0, 0, 0, 15, 0, 0,
	0, 0, 25, 0, 24, 0, 29, 0, 0, 0,
	0, 23, 85, 0, 33, 16, 19, 20, 21, 32,
	17, 0, 0, 18, 34, 35, 0, 0, 0, 0,
	22, 0, 0, 0, 0, 15, 0, 0, 0, 0,
	25, 0, 24, 0, 29, 0, 0, 0, 38, 23,
	0, 0, 33, 16, 19, 20, 21, 32, 17, 0,
	0, 18, 34, 35, 0, 0, 0, 0, 22, 0,
	0, 0, 0, 15, 0, 0, 0, 0, 25, 0,
	24, 0, 29, 0, 0, 6, 0, 23, 0, 0,
	33, 16, 19, 20, 21, 32, 17, 0, 0, 18,
	34, 35, 0, 0, 0, 0, 22, 0, 0, 0,
	0, 15, 0, 0, 0, 0, 25, 0, 24, 0,
	29, 0, 0, 0, 0, 23, 0, 0, 33, 16,
	19, 20, 95, 32, 17, 0, 0, 18, 34, 35,
	0, 0, 0, 0, 22, 0, 0, 0, 0, 15,
	0, 0, 0, 0, 25, 0, 24, 0, 29, 0,
	0, 134, 63, 23, 0, 0, 33, 34, 35, 0,
	0, 0, 130, 131, 0, 0, 0, 0, 0, 132,
	133, 0, 129, 25, 0, 24, 134, 63, 158, 0,
	0, 0, 34, 35, 0, 0, 0, 130, 131, 0,
	0, 0, 0, 0, 132, 133, 0, 129, 25, 0,
	24, 134, 63, 157, 0, 0, 0, 34, 35, 0,
	0, 0, 130, 131, 0, 0, 0, 0, 0, 132,
	133, 0, 129, 25, 0, 24, 134, 63, 156, 0,
	0, 0, 34, 35, 0, 0, 0, 130, 131, 0,
	0, 0, 0, 0, 132, 133, 0, 129, 25, 0,
	24, 134, 63, 155, 0, 0, 0, 34, 35, 0,
	0, 0, 130, 131, 0, 0, 0, 0, 0, 132,
	133, 0, 129, 25, 0, 24, 134, 63, 154, 0,
	0, 0, 34, 35, 0, 0, 0, 130, 131, 0,
	0, 0, 0, 0, 132, 133, 0, 129, 25, 0,
	24, 134, 63, 152, 0, 0, 0, 34, 35, 0,
	0, 0, 130, 131, 0, 0, 0, 0, 0, 132,
	133, 0, 129, 25, 0, 24, 134, 63, 149, 0,
	0, 0, 34, 35, 0, 0, 0, 130, 131, 0,
	0, 0, 0, 0, 132, 133, 0, 129, 25, 0,
	24, 0, 0, 146, 43, 44, 47, 50, 48, 49,
	0, 45, 46, 0, 0, 134, 63, 0, 0, 0,
	92, 34, 35, 0, 0, 0, 130, 131, 0, 0,
	0, 0, 0, 132, 133, 0, 129, 25, 0, 24,
	42, 43, 44, 47, 50, 48, 49, 0, 45, 46,
}

var StracePact = [...]int16{
	7, -1000, 51, 319, 7, 281, -5, 41, -1000, -1000,
	-1000, -1000, -1000, -1000, 653, 9, -1000, -1000, -1000, -1000,
	-1000, 8, 158, -1000, 357, 357, 122, 91, -1000, 46,
	-1000, -1000, 44, 34, -1000, -1000, -1000, -18, -6, -14,
	-16, 357, 357, 46, 46, 46, 46, 46, 46, 46,
	46, -1000, -1000, 46, 357, 243, 357, 121, -1000, -27,
	54, 106, -1000, -1000, -1000, 616, 395, -39, -1000, -28,
	-31, 78, 217, -1000, -1000, 202, 171, 72, 72, 141,
	96, 216, -1000, 19, -1000, 357, -1000, 59, 357, -1000,
	205, -1000, -1000, -23, -8, 50, 131, 110, 88, -1000,
	66, 64, -1000, -1000, -1000, -32, -1000, -1000, -1000, -1000,
	-1000, 126, -10, 63, 47, -1000, -1000, 638, 23, 638,
	12, 357, -1000, 4, 638, 3, 638, 599, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 638, 574,
	638, -1000, 638, 549, 638, 524, -1000, -1000, 499, -1000,
	474, 449, -1000, 424, -1000, -1000, -1000, -1000, -1000,
}

var StracePgo = [...]uint8{
	0, 142, 186, 1, 30, 185, 9, 0, 180, 49,
	63, 178, 46, 62, 161, 156, 153, 6,
}

var StraceR1 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 10,
	10, 9, 9, 9, 9, 9, 9, 9, 9, 9,
	17, 17, 17, 12, 12, 12, 12, 12, 12, 12,
	12, 13, 13, 13, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 13, 15, 15, 14, 14, 8, 11,
	11, 11, 16, 16, 16, 6, 6, 6, 2, 2,
	2, 2, 2, 5, 5, 5, 5, 5, 4, 4,
	7, 3, 3,
}

var StraceR2 = [...]int8{
	0, 4, 5, 6, 5, 5, 5, 8, 8, 9,
	9, 6, 6, 6, 10, 10, 9, 9, 2, 1,
	2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	0, 1, 3, 1, 1, 1, 1, 1, 1, 3,
	2, 1, 1, 1, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 2, 1, 2, 1, 2, 4, 4,
	4, 5, 2, 4, 1, 3, 3, 4, 2, 3,
	3, 4, 6, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 2,
}

var StraceChk = [...]int16{
	-1000, -1, 7, 37, 13, 33, 36, -17, -12, -5,
	-2, -16, -6, -8, -13, 24, 4, 9, 12, 5,
	6, 7, 19, 38, 31, 29, -14, -15, -11, 33,
	-7, -4, 8, 41, 13, 14, -1, -17, 37, 34,
	34, 28, 17, 18, 19, 25, 26, 20, 22, 23,
	21, -6, -13, 24, 33, 35, 40, 31, 7, 14,
	-17, -17, -7, 8, -4, -13, 33, 33, 36, 34,
	34, 35, 35, -12, -12, -13, -13, -13, -13, -13,
	-13, -13, -13, -17, -12, 39, -12, 8, 35, 32,
	28, 30, 34, -17, -3, 7, 41, 35, 35, 16,
	13, 14, 16, 34, -12, 32, -12, 30, 34, 34,
	-3, 7, 7, 13, 14, 16, 13, 33, 8, 33,
	8, 35, 34, 8, 33, 8, 33, -10, -9, 28,
	18, 19, 25, 26, 7, -6, -7, -4, 33, -10,
	33, -12, 33, -10, 33, -10, 34, -9, -10, 34,
	-10, -10, 34, -10, 34, 34, 34, 34, 34,
}

var StraceDef = [...]int8{
	0, -2, 0, 30, 0, 30, 0, 0, 31, 33,
	34, 35, 36, 37, 38, 0, 73, 74, 75, 76,
	77, 0, 0, 64, 30, 30, 41, 42, 43, 0,
	56, 54, 80, 0, 78, 79, 18, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 40, 53, 0, 30, 68, 0, 0, 62, 0,
	0, 0, 57, 80, 55, 0, 30, 0, 1, 0,
	0, 0, 0, 32, 39, 44, 45, 46, 47, 48,
	49, 50, 52, 0, 69, 0, 70, 0, 0, 65,
	0, 66, 51, 0, 0, 81, 0, 0, 0, 2,
	4, 5, 6, 58, 71, 0, 63, 67, 59, 60,
	82, 81, 0, 11, 12, 13, 3, 0, 0, 0,
	0, 0, 61, 0, 0, 0, 0, 0, 19, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 0, 0,
	0, 72, 0, 0, 0, 0, 8, 20, 0, 7,
	0, 0, 16, 0, 17, 10, 9, 14, 15,
}

var StraceTok1 = [...]int8{
	1,
}

var StraceTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44,
}

var StraceTok3 = [...]int8{
	0,
}

var StraceErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	StraceDebug        = 0
	StraceErrorVerbose = false
)

type StraceLexer interface {
	Lex(lval *StraceSymType) int
	Error(s string)
}

type StraceParser interface {
	Parse(StraceLexer) int
	Lookahead() int
}

type StraceParserImpl struct {
	lval  StraceSymType
	stack [StraceInitialStackSize]StraceSymType
	char  int
}

func (p *StraceParserImpl) Lookahead() int {
	return p.char
}

func StraceNewParser() StraceParser {
	return &StraceParserImpl{}
}

const StraceFlag = -1000

func StraceTokname(c int) string {
	if c >= 1 && c-1 < len(StraceToknames) {
		if StraceToknames[c-1] != "" {
			return StraceToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func StraceStatname(s int) string {
	if s >= 0 && s < len(StraceStatenames) {
		if StraceStatenames[s] != "" {
			return StraceStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func StraceErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !StraceErrorVerbose {
		return "syntax error"
	}

	for _, e := range StraceErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + StraceTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(StracePact[state])
	for tok := TOKSTART; tok-1 < len(StraceToknames); tok++ {
		if n := base + tok; n >= 0 && n < StraceLast && int(StraceChk[int(StraceAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if StraceDef[state] == -2 {
		i := 0
		for StraceExca[i] != -1 || int(StraceExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; StraceExca[i] >= 0; i += 2 {
			tok := int(StraceExca[i])
			if tok < TOKSTART || StraceExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if StraceExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += StraceTokname(tok)
	}
	return res
}

func Stracelex1(lex StraceLexer, lval *StraceSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(StraceTok1[0])
		goto out
	}
	if char < len(StraceTok1) {
		token = int(StraceTok1[char])
		goto out
	}
	if char >= StracePrivate {
		if char < StracePrivate+len(StraceTok2) {
			token = int(StraceTok2[char-StracePrivate])
			goto out
		}
	}
	for i := 0; i < len(StraceTok3); i += 2 {
		token = int(StraceTok3[i+0])
		if token == char {
			token = int(StraceTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(StraceTok2[1]) /* unknown char */
	}
	if StraceDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", StraceTokname(token), uint(char))
	}
	return char, token
}

func StraceParse(Stracelex StraceLexer) int {
	return StraceNewParser().Parse(Stracelex)
}

func (Stracercvr *StraceParserImpl) Parse(Stracelex StraceLexer) int {
	var Stracen int
	var StraceVAL StraceSymType
	var StraceDollar []StraceSymType
	_ = StraceDollar // silence set and not used
	StraceS := Stracercvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	Stracestate := 0
	Stracercvr.char = -1
	Stracetoken := -1 // Stracercvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		Stracestate = -1
		Stracercvr.char = -1
		Stracetoken = -1
	}()
	Stracep := -1
	goto Stracestack

ret0:
	return 0

ret1:
	return 1

Stracestack:
	/* put a state and value onto the stack */
	if StraceDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", StraceTokname(Stracetoken), StraceStatname(Stracestate))
	}

	Stracep++
	if Stracep >= len(StraceS) {
		nyys := make([]StraceSymType, len(StraceS)*2)
		copy(nyys, StraceS)
		StraceS = nyys
	}
	StraceS[Stracep] = StraceVAL
	StraceS[Stracep].yys = Stracestate

Stracenewstate:
	Stracen = int(StracePact[Stracestate])
	if Stracen <= StraceFlag {
		goto Stracedefault /* simple state */
	}
	if Stracercvr.char < 0 {
		Stracercvr.char, Stracetoken = Stracelex1(Stracelex, &Stracercvr.lval)
	}
	Stracen += Stracetoken
	if Stracen < 0 || Stracen >= StraceLast {
		goto Stracedefault
	}
	Stracen = int(StraceAct[Stracen])
	if int(StraceChk[Stracen]) == Stracetoken { /* valid shift */
		Stracercvr.char = -1
		Stracetoken = -1
		StraceVAL = Stracercvr.lval
		Stracestate = Stracen
		if Errflag > 0 {
			Errflag--
		}
		goto Stracestack
	}

Stracedefault:
	/* default state action */
	Stracen = int(StraceDef[Stracestate])
	if Stracen == -2 {
		if Stracercvr.char < 0 {
			Stracercvr.char, Stracetoken = Stracelex1(Stracelex, &Stracercvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if StraceExca[xi+0] == -1 && int(StraceExca[xi+1]) == Stracestate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			Stracen = int(StraceExca[xi+0])
			if Stracen < 0 || Stracen == Stracetoken {
				break
			}
		}
		Stracen = int(StraceExca[xi+1])
		if Stracen < 0 {
			goto ret0
		}
	}
	if Stracen == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			Stracelex.Error(StraceErrorMessage(Stracestate, Stracetoken))
			Nerrs++
			if StraceDebug >= 1 {
				__yyfmt__.Printf("%s", StraceStatname(Stracestate))
				__yyfmt__.Printf(" saw %s\n", StraceTokname(Stracetoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for Stracep >= 0 {
				Stracen = int(StracePact[StraceS[Stracep].yys]) + StraceErrCode
				if Stracen >= 0 && Stracen < StraceLast {
					Stracestate = int(StraceAct[Stracen]) /* simulate a shift of "error" */
					if int(StraceChk[Stracestate]) == StraceErrCode {
						goto Stracestack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if StraceDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", StraceS[Stracep].yys)
				}
				Stracep--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if StraceDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", StraceTokname(Stracetoken))
			}
			if Stracetoken == StraceEofCode {
				goto ret1
			}
			Stracercvr.char = -1
			Stracetoken = -1
			goto Stracenewstate /* try again in the same state */
		}
	}

	/* reduction by production Stracen */
	if StraceDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", Stracen, StraceStatname(Stracestate))
	}

	Stracent := Stracen
	Stracept := Stracep
	_ = Stracept // guard against "declared and not used"

	Stracep -= int(StraceR2[Stracen])
	// Stracep is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if Stracep+1 >= len(StraceS) {
		nyys := make([]StraceSymType, len(StraceS)*2)
		copy(nyys, StraceS)
		StraceS = nyys
	}
	StraceVAL = StraceS[Stracep+1]

	/* consult goto table to find next state */
	Stracen = int(StraceR1[Stracen])
	Straceg := int(StracePgo[Stracen])
	Stracej := Straceg + StraceS[Stracep].yys + 1

	if Stracej >= StraceLast {
		Stracestate = int(StraceAct[Straceg])
	} else {
		Stracestate = int(StraceAct[Stracej])
		if int(StraceChk[Stracestate]) != -Stracen {
			Stracestate = int(StraceAct[Straceg])
		}
	}
	// dummy call; replaced with literal code
	switch Stracent {

	case 1:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line strace.y:74
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, int64(-1), true, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 2:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line strace.y:77
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", nil, -1, true, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 3:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line strace.y:82
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, nil, int64(StraceDollar[6].val_int), false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 4:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line strace.y:87
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, int64(StraceDollar[5].val_int), false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 5:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line strace.y:89
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, int64(StraceDollar[5].val_uint), false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 6:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line strace.y:91
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, -1, false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 7:
		StraceDollar = StraceS[Stracept-8 : Stracept+1]
//line strace.y:93
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, int64(StraceDollar[5].val_uint), false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 8:
		StraceDollar = StraceS[Stracept-8 : Stracept+1]
//line strace.y:95
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, StraceDollar[5].val_int, false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 9:
		StraceDollar = StraceS[Stracept-9 : Stracept+1]
//line strace.y:97
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, int64(StraceDollar[5].val_uint), false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 10:
		StraceDollar = StraceS[Stracept-9 : Stracept+1]
//line strace.y:99
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, int64(StraceDollar[5].val_int), false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 11:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line strace.y:102
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, StraceDollar[6].val_int, false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 12:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line strace.y:105
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, int64(StraceDollar[6].val_uint), false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 13:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line strace.y:108
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, -1, false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 14:
		StraceDollar = StraceS[Stracept-10 : Stracept+1]
//line strace.y:111
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, StraceDollar[6].val_int, false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 15:
		StraceDollar = StraceS[Stracept-10 : Stracept+1]
//line strace.y:114
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, int64(StraceDollar[6].val_uint), false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 16:
		StraceDollar = StraceS[Stracept-9 : Stracept+1]
//line strace.y:117
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, StraceDollar[6].val_int, false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 17:
		StraceDollar = StraceS[Stracept-9 : Stracept+1]
//line strace.y:120
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, int64(StraceDollar[6].val_uint), false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 18:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:124
		{
			call := StraceDollar[2].val_syscall
			call.Pid = StraceDollar[1].val_int
			Stracelex.(*Stracelexer).result = call
		}
	case 19:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:127
		{
			StraceVAL.val_parenthetical = newParenthetical()
		}
	case 20:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:128
		{
			StraceVAL.val_parenthetical = newParenthetical()
		}
	case 21:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:131
		{
			StraceVAL.val_parenthetical = newParenthetical()
		}
	case 22:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:132
		{
			StraceVAL.val_parenthetical = newParenthetical()
		}
	case 23:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:133
		{
			StraceVAL.val_parenthetical = newParenthetical()
		}
	case 24:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:134
		{
			StraceVAL.val_parenthetical = newParenthetical()
		}
	case 25:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:135
		{
			StraceVAL.val_parenthetical = newParenthetical()
		}
	case 26:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:136
		{
			StraceVAL.val_parenthetical = newParenthetical()
		}
	case 27:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:137
		{
			StraceVAL.val_parenthetical = newParenthetical()
		}
	case 28:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:138
		{
			StraceVAL.val_parenthetical = newParenthetical()
		}
	case 29:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:139
		{
			StraceVAL.val_parenthetical = newParenthetical()
		}
	case 30:
		StraceDollar = StraceS[Stracept-0 : Stracept+1]
//line strace.y:142
		{
			StraceVAL.val_types = make([]IrType, 0)
		}
	case 31:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:143
		{
			StraceVAL.val_types = []IrType{StraceDollar[1].val_type}
		}
	case 32:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:144
		{
			StraceDollar[1].val_types = append(StraceDollar[1].val_types, StraceDollar[3].val_type)
			StraceVAL.val_types = StraceDollar[1].val_types
		}
	case 33:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:148
		{
			StraceVAL.val_type = StraceDollar[1].val_buf_type
		}
	case 34:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:149
		{
			StraceVAL.val_type = StraceDollar[1].val_field
		}
	case 35:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:150
		{
			StraceVAL.val_type = StraceDollar[1].val_pointer_type
		}
	case 36:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:151
		{
			StraceVAL.val_type = StraceDollar[1].val_group_type
		}
	case 37:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:152
		{
			StraceVAL.val_type = StraceDollar[1].val_call
		}
	case 38:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:153
		{
			StraceVAL.val_type = StraceDollar[1].val_type
		}
	case 39:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:154
		{
			StraceVAL.val_type = newDynamicType(StraceDollar[1].val_type, StraceDollar[3].val_type)
		}
	case 40:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:155
		{
			StraceVAL.val_type = StraceDollar[2].val_group_type
		}
	case 41:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:159
		{
			StraceVAL.val_type = StraceDollar[1].val_type
		}
	case 42:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:160
		{
			StraceVAL.val_type = StraceDollar[1].val_type
		}
	case 43:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:161
		{
			StraceVAL.val_type = StraceDollar[1].val_macro
		}
	case 44:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:162
		{
			StraceVAL.val_type = newBinop(StraceDollar[1].val_type, StraceDollar[3].val_type, orOp)
		}
	case 45:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:163
		{
			StraceVAL.val_type = newBinop(StraceDollar[1].val_type, StraceDollar[3].val_type, andOp)
		}
	case 46:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:164
		{
			StraceVAL.val_type = newBinop(StraceDollar[1].val_type, StraceDollar[3].val_type, lshiftOp)
		}
	case 47:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:165
		{
			StraceVAL.val_type = newBinop(StraceDollar[1].val_type, StraceDollar[3].val_type, rshiftOp)
		}
	case 48:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:166
		{
			StraceVAL.val_type = newBinop(StraceDollar[1].val_type, StraceDollar[3].val_type, lorOp)
		}
	case 49:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:167
		{
			StraceVAL.val_type = newBinop(StraceDollar[1].val_type, StraceDollar[3].val_type, landOp)
		}
	case 50:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:168
		{
			StraceVAL.val_type = newBinop(StraceDollar[1].val_type, StraceDollar[3].val_type, lequalOp)
		}
	case 51:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:169
		{
			StraceVAL.val_type = StraceDollar[2].val_type
		}
	case 52:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:170
		{
			StraceVAL.val_type = newBinop(StraceDollar[1].val_type, StraceDollar[3].val_type, timesOp)
		}
	case 53:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:171
		{
			StraceVAL.val_type = newUnop(StraceDollar[2].val_type, onescompOp)
		}
	case 54:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:174
		{
			i := make(Ints, 1)
			i[0] = StraceDollar[1].val_int_type
			StraceVAL.val_type = i
		}
	case 55:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:175
		{
			StraceVAL.val_type = append(StraceDollar[1].val_type.(Ints), StraceDollar[2].val_int_type)
		}
	case 56:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:178
		{
			f := make(Flags, 1)
			f[0] = StraceDollar[1].val_flag_type
			StraceVAL.val_type = f
		}
	case 57:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:179
		{
			StraceVAL.val_type = append(StraceDollar[1].val_type.(Flags), StraceDollar[2].val_flag_type)
		}
	case 58:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line strace.y:182
		{
			StraceVAL.val_call = newCallType(StraceDollar[1].data, StraceDollar[3].val_types)
		}
	case 59:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line strace.y:185
		{
			StraceVAL.val_macro = newMacroType(StraceDollar[1].data, StraceDollar[3].val_types)
		}
	case 60:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line strace.y:186
		{
			StraceVAL.val_macro = newMacroType(StraceDollar[1].data, nil)
		}
	case 61:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line strace.y:187
		{
			StraceVAL.val_macro = newMacroType(StraceDollar[4].data, nil)
		}
	case 62:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:190
		{
			StraceVAL.val_pointer_type = nullPointer()
		}
	case 63:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line strace.y:191
		{
			StraceVAL.val_pointer_type = NewPointerType(StraceDollar[2].val_uint, StraceDollar[4].val_type)
		}
	case 64:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:192
		{
			StraceVAL.val_pointer_type = nullPointer()
		}
	case 65:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:195
		{
			StraceVAL.val_group_type = newGroupType(StraceDollar[2].val_types)
		}
	case 66:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:196
		{
			StraceVAL.val_group_type = newGroupType(StraceDollar[2].val_types)
		}
	case 67:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line strace.y:197
		{
			StraceVAL.val_group_type = newGroupType(StraceDollar[2].val_types)
		}
	case 68:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:200
		{
			StraceVAL.val_field = newField(StraceDollar[1].data, nil)
		}
	case 69:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:201
		{
			StraceVAL.val_field = newField(StraceDollar[1].data, StraceDollar[3].val_type)
		}
	case 70:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line strace.y:202
		{
			StraceVAL.val_field = newField(StraceDollar[1].data, StraceDollar[3].val_type)
		}
	case 71:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line strace.y:203
		{
			StraceVAL.val_field = newField(StraceDollar[1].data, StraceDollar[4].val_type)
		}
	case 72:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line strace.y:204
		{
			StraceVAL.val_field = newField(StraceDollar[1].data, StraceDollar[6].val_type)
		}
	case 73:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:207
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	case 74:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:208
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	case 75:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:209
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	case 76:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:210
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	case 77:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:211
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	case 78:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:215
		{
			StraceVAL.val_int_type = newIntType(StraceDollar[1].val_int)
		}
	case 79:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:216
		{
			StraceVAL.val_int_type = newIntType(int64(StraceDollar[1].val_uint))
		}
	case 80:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:219
		{
			StraceVAL.val_flag_type = newFlagType(StraceDollar[1].data)
		}
	case 81:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line strace.y:222
		{
			ids := make([]*BufferType, 0)
			ids = append(ids, newBufferType(StraceDollar[1].data))
			StraceVAL.val_identifiers = ids
		}
	case 82:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line strace.y:223
		{
			StraceDollar[2].val_identifiers = append(StraceDollar[2].val_identifiers, newBufferType(StraceDollar[1].data))
			StraceVAL.val_identifiers = StraceDollar[2].val_identifiers
		}
	}
	goto Stracestack /* stack new state and value */
}
